//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.09 at 07:34:54 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://something.com/books", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.something.books;
